@extends('layouts.admin')
@section('title', $storageItem->name)
@section('eyebrow', 'Storage · Kartu stok')
@section('heading', $storageItem->name)
@section('content')
    <section class="admin-page-heading"><div><h1>{{ $storageItem->name }}</h1><p>{{ $storageItem->code }} · {{ $storageItem->category }} · satuan {{ $storageItem->unit }}</p></div><div class="admin-actions"><a class="button button--outline admin-button" href="{{ route('admin.storage-items.index') }}">&larr; Daftar stok</a>@can('storage.items.manage')<a class="button button--primary admin-button" href="{{ route('admin.storage-items.edit', $storageItem) }}">Edit barang</a>@endcan</div></section>
    <section class="storage-stock-location-grid">@forelse($storageItem->stocks as $stock)<article class="storage-stock-location"><span>{{ $stock->location->name }}</span><strong>{{ format_quantity($stock->quantity) }} {{ $storageItem->unit }}</strong><small>{{ $stock->location->fullName() }}</small></article>@empty<article class="storage-stock-location"><span>Belum ada saldo</span><strong>0 {{ $storageItem->unit }}</strong><small>Catat penerimaan pertama untuk barang ini.</small></article>@endforelse</section>
    <section class="admin-panel"><header class="admin-panel__header"><div><h2>Kartu stok</h2><p>Riwayat pergerakan dari transaksi yang telah dicatat.</p></div></header>
        @if($movements->isEmpty())<div class="admin-empty"><h2>Belum ada pergerakan stok</h2></div>@else<x-ui.table class="admin-table-wrap"><thead><tr><th>Tanggal</th><th>Nomor</th><th>Lokasi</th><th>Keterangan</th><th>Masuk</th><th>Keluar</th></tr></thead><tbody>@foreach($movements as $line)<tr><td>{{ $line->transaction->transaction_date->format('d/m/Y') }}</td><td><strong>{{ $line->transaction->number }}</strong><small>{{ ucfirst($line->transaction->type) }}</small></td><td>{{ $line->transaction->location->name }}</td><td>{{ $line->transaction->purpose ?? $line->transaction->supplier ?? $line->transaction->reference ?? 'Tanpa keterangan' }}</td><td>{{ in_array($line->transaction->type,['receipt','return']) || ($line->transaction->type==='adjustment' && (float)$line->quantity>0) ? format_quantity(abs((float)$line->quantity)).' '.$storageItem->unit : '0' }}</td><td>{{ $line->transaction->type==='issue' || ($line->transaction->type==='adjustment' && (float)$line->quantity<0) ? format_quantity(abs((float)$line->quantity)).' '.$storageItem->unit : '0' }}</td></tr>@endforeach</tbody></x-ui.table><x-ui.pagination :paginator="$movements" />@endif
    </section>
@endsection
@push('styles')<link rel="stylesheet" href="{{ asset('templates/welding-school/storage.css') }}?v={{ filemtime(public_path('templates/welding-school/storage.css')) }}">@endpush
