@extends('layouts.admin')
@section('title', 'Laporan Storage')
@section('eyebrow', 'Storage')
@section('heading', 'Laporan Storage')
@section('content')
    <section class="admin-page-heading"><div><h1>Laporan Storage</h1><p>Telusuri pergerakan consumable dan pinjaman aset yang terlambat.</p></div><div class="admin-actions"><a class="button button--outline admin-button" href="{{ route('admin.storage.reports.excel', request()->only(['from','to','location_id','storage_item_id'])) }}"><x-ui.icon name="download" size="16" /> Excel</a><a class="button button--outline admin-button" href="{{ route('admin.storage.reports.pdf', request()->only(['from','to','location_id','storage_item_id'])) }}"><x-ui.icon name="file" size="16" /> PDF</a></div></section>
    <form class="admin-filter storage-report-filter" method="GET"><label class="admin-field"><span>Dari tanggal</span><input type="date" name="from" value="{{ request('from') }}"></label><label class="admin-field"><span>Sampai tanggal</span><input type="date" name="to" value="{{ request('to') }}"></label><label class="admin-field"><span>Lokasi</span><select name="location_id"><option value="">Semua lokasi</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected((string)request('location_id')===(string)$location->id)>{{ $location->name }}</option>@endforeach</select></label><label class="admin-field"><span>Consumable</span><select name="storage_item_id"><option value="">Semua barang</option>@foreach($items as $item)<option value="{{ $item->id }}" @selected((string)request('storage_item_id')===(string)$item->id)>{{ $item->code }} · {{ $item->name }}</option>@endforeach</select></label><div class="admin-actions"><button class="button button--primary admin-button">Terapkan</button><a class="button button--outline admin-button" href="{{ route('admin.storage.reports.index') }}">Reset</a></div></form>
    @if($overdueLoans->isNotEmpty())<section class="admin-panel storage-overdue-panel"><header class="admin-panel__header"><div><h2>Pinjaman terlambat</h2><p>{{ $overdueLoans->sum(fn($loan) => $loan->items->count()) }} aset melewati tanggal kembali.</p></div></header><div class="storage-overdue-list">@foreach($overdueLoans as $loan)<article><div><strong>{{ $loan->items->pluck('asset.equipment_name')->filter()->join(', ') }}</strong><small>{{ $loan->borrower?->name ?? $loan->borrower_name }}</small></div><span>Seharusnya {{ $loan->due_at->format('d M Y H:i') }}</span></article>@endforeach</div></section>@endif
    <section class="admin-panel"><header class="admin-panel__header"><div><h2>Pergerakan stok</h2><p>{{ $movements->total() }} baris transaksi sesuai filter.</p></div></header>
        @if($movements->isEmpty())<div class="admin-empty"><h2>Tidak ada data</h2><p>Ubah filter atau mulai mencatat transaksi Storage.</p></div>@else<x-ui.table class="admin-table-wrap"><thead><tr><th>Tanggal</th><th>Nomor</th><th>Consumable</th><th>Lokasi</th><th>Jenis</th><th>Jumlah</th><th>Tujuan / Sumber</th></tr></thead><tbody>@foreach($movements as $line)<tr><td>{{ $line->transaction->transaction_date->format('d/m/Y') }}</td><td>{{ $line->transaction->number }}</td><td><strong>{{ $line->item->name }}</strong><small>{{ $line->item->code }}</small></td><td>{{ $line->transaction->location->name }}</td><td>{{ ucfirst($line->transaction->type) }}</td><td><strong>{{ format_quantity($line->quantity) }} {{ $line->item->unit }}</strong></td><td>{{ $line->transaction->purpose ?? $line->transaction->supplier ?? $line->transaction->reference ?? 'Tidak dicatat' }}@if($line->transaction->trainingBatch)<small>{{ $line->transaction->trainingBatch->code }}</small>@endif</td></tr>@endforeach</tbody></x-ui.table><x-ui.pagination :paginator="$movements" />@endif
    </section>
@endsection
@push('styles')<link rel="stylesheet" href="{{ asset('templates/welding-school/storage.css') }}?v={{ filemtime(public_path('templates/welding-school/storage.css')) }}">@endpush
